### PR TITLE
fix StopIteration exception for Python 3.7+

### PR DESCRIPTION
**Pull request by nkgilley**

### CODE REVIEW

**Comment by sublee** [comment]
Thank you for submitting a PR but I don't understand what is this PR for. Isn't `return` in a generator equivalent to `raise StopIteration`?

**Comment by nkgilley** [comment]
see https://stackoverflow.com/a/51701040

> PEP 479 is enabled for all code in Python 3.7, meaning that StopIteration exceptions raised directly or indirectly in coroutines and generators are transformed into RuntimeError exceptions. (Contributed by Yury Selivanov in bpo-32670.)

**Comment by sublee** [comment]
Oh, I got it. It looks great. However, this PR should not include version bumping or adding supported Python versions. Please separate to isolate the context.

**Comment by michael-robbins** [comment]
Is this good to merge @sublee ?

**Comment by sublee** [comment]
Sorry for the late response. Thank you to notify me.

**Comment by sublee** [comment]
Ranking v0.3.2 which supports Python 3.4+ is released.

**Pull request merged**
